---
- name: Install Apache 2
  hosts: web
  tasks:
    - name: Install Apache 2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Enable and start Apache 2 service
      service:
        name: apache2
        enabled: yes
        state: started
