---
- name: Install webserver
  hosts: proxy
  vars:
    apache_package: "httpd"
    apache_service: "httpd"
    # hello_string: "Hi"

  tasks:
    - name: Install Apache
      package: name={{ apache_package }} state=installed
      tags: install upgrade

    - name: Set Apache virtual host
      template:
        src: ../templates/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
        validate: /usr/sbin/httpd -t -f %s
      notify: Restart Apache
      tags: config

    - name: Set index.html
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        owner: apache
        group: apache
      tags: index

    - name: Enable and start Apache service
      service:
        name: "{{ apache_service }}"
        enabled: yes
        state: started
      tags: start

  handlers:
    - name: Restart Apache
      service:
        name: "{{ apache_service }}"
        state: restarted
